


IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'CLIENTES' AND  COLUMN_NAME = 'CPF')
BEGIN
	ALTER TABLE CLIENTES ADD CPF VARCHAR(14) NOT NULL
	PRINT('Coluna CPF adicionada na tabela CLIENTES com sucesso');	
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'BENEFICIARIOS' AND  COLUMN_NAME = 'CPF')
BEGIN
	ALTER TABLE BENEFICIARIOS ALTER COLUMN [CPF] VARCHAR(14) NOT NULL;
	PRINT('Coluna CPF adicionada na tabela BENEFICIARIOS com sucesso');	
END
GO



