


CREATE OR ALTER PROCEDURE FI_SP_InsereOuAlteraBeneficiario
	@ID				BIGINT = NULL,
    @NOME          VARCHAR (50) ,
    @CPF           VARCHAR (14),
	@IDCLIENTE		BIGINT
AS
BEGIN

	--IF (@ID IS NULL OR @ID = 0)
	IF (ISNULL(@ID,0) = 0)
		BEGIN
			INSERT INTO BENEFICIARIOS (NOME, CPF, IDCLIENTE) 
			VALUES (@NOME, @CPF, @IDCLIENTE)

			SELECT SCOPE_IDENTITY()
		END
	ELSE
		BEGIN
			/*
			*/
			UPDATE BENEFICIARIOS 
			SET 
				NOME = @NOME, 
				IDCLIENTE = @IDCLIENTE,
				CPF = @CPF
			WHERE Id = @Id
		END
END
GO
